project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


accounts/models.py
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.db import models
from datetime import timedelta

User = get_user_model()
    
class Employee(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    contact = models.CharField(max_length=15,blank=True)
    image = models.ImageField(upload_to='products',blank=True,null=True)
    job_title = models.CharField(max_length=50,blank=True)
    years_of_working = models.PositiveIntegerField(default=0)
    gender = models.CharField(max_length=1,choices=[('M','Male'),('F','Female'),('O','Other')],blank=True)
    department = models.CharField(max_length=50,blank=True)
    hire_date = models.DateTimeField(auto_now_add=True)
    salary = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    designation = models.CharField(choices=[('E','Employee'),('H','HR Manager'),('A','Admin')],max_length=1)

    def __str__(self):
        return self.user.username
    
class OTP(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    otp = models.CharField(max_length=6)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def is_valid(self):
        return now() < self.expires_at
    
class Leave(models.Model):
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    reason = models.TextField(blank=True, null=True)

    def total_leave_days(self):
        return (self.end_date - self.start_date).days + 1

    def save(self, *args, **kwargs):
        leave_days = self.total_leave_days()
        if leave_days <= 0:
            raise ValueError("End date must be after or equal to the start date.")
        current_month_start = self.start_date.replace(day=1)
        next_month_start = (current_month_start + timedelta(days=31)).replace(day=1)
        existing_leaves = Leave.objects.filter(employee=self.employee,start_date__gte=current_month_start,start_date__lt=next_month_start)
        total_days = sum(leave.total_leave_days() for leave in existing_leaves)
        if total_days + leave_days > 3:
            raise ValueError("An employee can't take more than 3 days leave in a month.")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.employee.user.username

class PerformanceAnalysis(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    month_start = models.DateField()
    goals_set = models.TextField(blank=True, null=True)    
    goals_achieved = models.TextField(blank=True, null=True) 
    manager_feedback = models.TextField(blank=True, null=True) 
    rating = models.DecimalField(max_digits=3, decimal_places=2)  
    created_at = models.DateTimeField(auto_now_add=True) 
    
    def get_goals_set(self):
        return self.goals_set.split(',')
    
    def get_goals_achieved(self):
        return self.goals_achieved.split(',')

    def __str__(self):
        return f"{self.employee.user.username} - {self.month_start.strftime("%B %Y")}"
    
    def save(self, *args, **kwargs):
        start = self.month_start.replace(day=1)
        existing_record = PerformanceAnalysis.objects.filter(
            employee=self.employee,
            month_start=start,
        ).first()

        if existing_record:
            existing_record.goals_set += ','+self.goals_set
            existing_record.goals_achieved += ','+self.goals_achieved
            existing_record.manager_feedback = self.manager_feedback
            existing_record.rating += self.rating
            existing_record.save()
        else:
            self.month_start = start
            super().save(*args, **kwargs)

templates/employees/apply_leave.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apply Leave</title>
    {% include "css.html" %}
</head>
<body>
    <div class="fixed inset-0 flex items-center justify-center bg-black/50 backdrop-blur-md z-50" data-messages-exist="{{ messages|length|yesno:'true,false' }}" id="popup" style="display:none">
        <div class="bg-white p-[2rem] flex flex-col justify-center items-center w-[40ch] rounded-lg shadow-lg">
            {% for message in messages %}
            <div class="text-lg font-semibold text-center">{{ message }}</div>
            {% endfor %}
            <button class="mt-[1rem] bg-sky-600 text-white px-4 py-2 rounded-lg" onclick="closePopup()">Close</button>
        </div>
    </div>
    <div class="min-h-[100dvh] flex justify-center items-center bg-slate-300">
        <form method="post" class="bg-white p-[2rem] gap-[1rem] flex flex-col items-center min-w-[30rem]">
            {% csrf_token %}
            <div class="text-4xl font-semibold p-[1rem_2rem] text-center">Leave Form</div>
            <div class="p-[1rem_2rem] flex gap-[1rem] items-center w-[80%]">
                <label class="basis-1/2 text-lg" for="start_date">Start Date</label>
                <input class="border-b-2 border-black outline-none basis-1/2" type="date" name="start_date" id="start_date">
            </div>
            <div class="p-[1rem_2rem] flex gap-[1rem] items-center w-[80%]">
                <label class="basis-1/2 text-lg" for="end_date">End Date</label>
                <input class="border-b-2 border-black outline-none basis-1/2" type="date" name="end_date" id="end_date">
            </div>
            <div class="relative p-[1rem_2rem] flex gap-[1rem] items-center w-[80%]">
            <textarea
              name="reason"
              id="reason"
              class="peer border-2 p-[1rem] border-black bg-transparent outline-none min-h-[10rem] w-full"
              placeholder=""
            >{{ request.POST.reason|default:"" }}</textarea>
            <label
              for="reason"
              class="absolute -top-[1rem] left-[2rem] peer-placeholder-shown:left-[3rem] text-sm transition-all peer-placeholder-shown:top-[2rem] peer-placeholder-shown:text-lg"
            >
              Reason
            </label>
            </div>
            <input class="bg-blue-600 hover:bg-blue-500 cursor-pointer p-[.8rem_1.8rem] rounded-xl font-semibold text-white text-lg" type="submit" value="Apply">
        </form>
    </div>
    <script>
        function showPopup() {
            const popup = document.getElementById("popup");
            popup.style.display = "flex";
            document.querySelector('#popup button').focus()
        }
      
        function closePopup() {
            const popup = document.getElementById("popup");
            popup.style.display = "none";
            document.querySelector('form #name').focus()
        }
      
        document.addEventListener("DOMContentLoaded", () => {
            const messagesExist = document.getElementById('popup').dataset.messagesExist === "true";
            if (messagesExist) {
                showPopup();
            }
        });
      </script>
</body>
</html>

templates/employees/employee.html
{% extends "index.html" %}
{% load static %}
{% block title %}Employee Profile{% endblock title %}
{% block content %}
<div class="fixed inset-0 flex items-center justify-center bg-black/50 backdrop-blur-md z-50" data-messages-exist="{{ messages|length|yesno:'true,false' }}" id="popup" style="display:none">
    <div class="bg-white p-[2rem] flex flex-col justify-center items-center w-[40ch] rounded-lg shadow-lg">
        {% for message in messages %}
        <div class="text-lg font-semibold text-center">{{ message }}</div>
        {% endfor %}
        <button class="mt-[1rem] bg-sky-600 text-white px-4 py-2 rounded-lg" onclick="closePopup()">Close</button>
    </div>
</div>
<div class="flex flex-col min-h-[100dvh] bg-slate-300">
    <div style="background: url({% static "images/profile_banner.png" %}) no-repeat center;background-size:cover;" class="relative h-[35dvh] before:content-[''] before:bg-[rgba(0,0,0,.4)] before:absolute before:inset-0"></div>
    <div class="relative flex min-h-[65dvh] justify-evenly items-start">
    <div class="absolute flex flex-col gap-[1rem] -top-[7rem] left-[5rem]">
        <img src="{{employee.image.url}}" alt="{{employee.user.username}}" class="size-[15rem] rounded-[100rem]">
        <div class="text-lg opacity-60 font-semibold">EMPLOYEE DETAILS</div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Name</div>
            <div class="text-lg capitalize font-semibold">{{ employee.user.username }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Gender</div>
            <div class="text-lg capitalize font-semibold">{{ employee.get_gender_display }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Contact</div>
            <div class="text-lg capitalize font-semibold">{{ employee.contact }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Position</div>
            <div class="text-lg capitalize font-semibold">{{ employee.job_title }}</div>
        </div>
    </div>
    <div class="w-[15rem]"></div>
    <div class="w-[16rem] flex flex-col gap-[1rem] mt-[5rem]">
        <div class="text-lg opacity-60 font-semibold">ROLE</div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Role</div>
            <div class="text-lg capitalize font-semibold">{{ employee.get_designation_display }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Department</div>
            <div class="text-lg capitalize font-semibold">{{ employee.department }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Experience</div>
            <div class="text-lg capitalize font-semibold">{{ employee.years_of_working }}</div>
        </div>
        <div class="flex flex-col bg-slate-200 p-[.3rem] mx-[.4rem] rounded-md">
            <div class="text-sm opacity-60">Date Joined</div>
            <div class="text-lg capitalize font-semibold">{{ employee.hire_date|date:"F j, Y" }}</div>
        </div>
    </div>
    <div class="flex flex-col mt-[10rem] gap-[2rem] justify-center">
        <a class="bg-blue-700 hover:bg-blue-600 p-[1rem_1.5rem] rounded-2xl text-lg text-white font-semibold" href="/update_profile/{{employee.user.id}}">Update Profile</a>
        <a class="bg-green-700 hover:bg-green-600 p-[1rem_1.5rem] rounded-2xl text-lg text-center text-white font-semibold" href="/apply_leave/">Apply Leave</a>
    </div>
    </div>
    <div class="flex lg:flex-row flex-col min-h-[40rem] border-t-[1px] border-black">
        <div class="flex flex-col gap-[1rem] basis-1/2 p-[2rem]">
            <div class="text-3xl font-semibold">Performance</div>
            <div class="relative h-[30rem] flex justify-center items-center">
                <canvas class="" id="performanceChart"></canvas>
            </div>
            <div>
                <label for="performance_year">Select Year:</label>
                <select id="performance_year" onchange="updatePerformanceChart({{employee.user.id}})">
                    {% for year in performance_years_list %}
                    <option value="{{ year }}" {% if year == now.year %}selected{% endif %}>
                        {{ year }}
                    </option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="flex flex-col gap-[1rem] basis-1/2 p-[2rem]">
            <div class="text-3xl font-semibold">Attendance</div>
            <div class="relative h-[30rem] flex justify-center items-center">
                <canvas class="" id="attendanceChart"></canvas>
            </div>
            <div class="flex gap-[1rem]">
                <label for="attendance_year">Year:</label>
                <select id="attendance_year" onchange="updateAttendanceChart({{employee.user.id}})">
                    {% for year in attendance_years_list %}
                    <option value="{{ year }}" {% if year == now.year %}selected{% endif %}>
                        {{ year }}
                    </option>
                    {% endfor %}
                </select>
        
                <label for="attendance_month">Month:</label>
                <select id="attendance_month" onchange="updateAttendanceChart({{employee.user.id}})">
                    {% for month in months %}
                    <option value="{{ month.0 }}" {% if month.0 == now.month %}selected{% endif %}>
                        {{ month.1 }}
                    </option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
      updatePerformanceChart({{ employee.user.id }});
      updateAttendanceChart({{ employee.user.id }});
    });
  </script>
{% endblock content %}

templates/employees/employees.html
{% extends "index.html" %}
{% load static %}
{% block title %}Employees{% endblock title %}
{% block content %}
<div class="grid grid-cols-3 gap-[2rem] p-[2rem]">
    <div class="col-span-2 row-span-2 flex flex-col items-center justify-center p-[1rem] shadow-[inset_20px_20px_80px_0px,inset_-20px_-20px_80px_0px]  shadow-slate-500 cursor-pointer" onclick="window.location.href='/employees/{{employee.user.id}}'">
        <img src="{% static "images/profile_banner.png" %}" alt="Profile Banner" class="-z-20 h-1/2 w-full object-cover object-center">
        <div class="relative w-full h-1/2">
            {% if employee.image %}
            <img class="size-[15rem] absolute -top-2/3 left-[10%] rounded-[1000rem]" src="{{ employee.image.url }}" alt="{{ employee.user.name }}">
            {% else %}
            <img class="size-[15rem] absolute -top-2/3 left-[10%] rounded-[1000rem]" src="{% static 'images/avatar.png' %}" alt="{{ employee.user.name }}">
            {% endif %}
            <div class="absolute right-1/4 flex flex-col items-center p-[2rem_4rem]">
                <div class="font-semibold text-2xl">{{ employee.user.username }}</div>
                <div class="">Job Role: {{ employee.job_title }}</div>
                <div class="">Designation: {{ employee.get_designation_display }}</div>
            </div>
        </div>
    </div>
    {% for employee in employees reversed %}
    <div class="flex items-center justify-between p-[1rem] shadow-lg hover:shadow-2xl cursor-pointer" onclick="window.location.href='/employees/{{employee.user.id}}'">
        {% if employee.image %}
        <img class="size-[10rem] rounded-[1000rem]" src="{{ employee.image.url }}" alt="{{ employee.user.name }}">
        {% else %}
        <img class="size-[10rem] rounded-[1000rem]" src="{% static 'images/avatar.png' %}" alt="{{ employee.user.name }}">
        {% endif %}
        <div class="flex flex-col items-center w-[60%]">
            <div class="font-semibold text-2xl">{{ employee.user.username }}</div>
            <div class="">Job Role: {{ employee.job_title }}</div>
            <div class="">Designation: {{ employee.get_designation_display }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/employees/profileupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee</title>
    {% include "css.html" %}
</head>
<body>
    <div class="flex justify-center items-center min-h-[100dvh] bg-slate-300">
        <form method="post" enctype="multipart/form-data" class="bg-white grid grid-cols-3 gap-[3rem] justify-items-center p-[2rem_2.5rem] items-center justify-center shadow-2xl">
            {% csrf_token %}
            <div class="font-semibold text-3xl p-[1rem_1.5rem] col-start-2">{{ employee.user.username }}'s Details</div>
            <div class="flex flex-col items-center justify-center row-start-2 gap-[1rem]">
                <img class="size-[4rem] border rounded-[10rem]" id="preview" src="{{employee.image.url}}" alt="{{employee.user.username}}">
                <label class="font-semibold text-sm cursor-pointer" id="file-label" for="image">Click here to update</label>
                <input type="file" id="image" name="image" class="hidden">
            </div>
            <div class="flex flex-col w-3/4 gap-[1rem] row-start-2 bg-slate-200 p-[.6rem] rounded-md">
                <label class="text-sm opacity-60" for="job_title">Job Role: </label>
                <input class="p-[.2rem_.7rem] bg-transparent border-b-2 border-black outline-none" value="{{employee.job_title}}" type="text" id="job_title" name="job_title">
            </div>
            <div class="flex flex-col w-3/4 gap-[1rem] row-start-2 bg-slate-200 p-[.6rem] rounded-md">
                <label class="text-sm opacity-60" for="gender">Gender: </label>
                <select name="gender" id="gender"
                class="block bg-transparent border-b-2 border-black px-[5rem] outline-none">
                <option value="M">Male</option>
                <option value="F">Female</option>
                <option value="O">Other</option>
                </select>
            </div>
            <div class="flex flex-col w-3/4 gap-[1rem] row-start-3 bg-slate-200 p-[.6rem] rounded-md">
                <label class="text-sm opacity-60" for="years_of_working">Experience: </label>
                <input class="p-[.2rem_.7rem] bg-transparent border-b-2 border-black outline-none" value="{{employee.years_of_working}}" type="text" name="years_of_working">
            </div>
            <div class="flex flex-col w-3/4 gap-[1rem] row-start-3 bg-slate-200 p-[.6rem] rounded-md">
                <label class="text-sm opacity-60" for="years_of_working">Department: </label>
                <input class="p-[.2rem_.7rem] bg-transparent border-b-2 border-black outline-none" value="{{employee.department}}" type="text" name="department">
            </div>
            <div class="flex flex-col w-3/4 gap-[1rem] row-start-3 bg-slate-200 p-[.6rem] rounded-md">
                <label class="text-sm opacity-60" for="years_of_working">Contact: </label>
                <input class="p-[.2rem_.7rem] bg-transparent border-b-2 border-black outline-none" value="{{employee.contact}}" type="text" name="contact">
            </div>
            <input class="bg-blue-700 p-[.7rem_1.2rem] cursor-pointer rounded-2xl text-lg text-white font-semibold" type="submit" value="Save Changes">
        </form>
    </div>
    <script>
        document.getElementById('image').addEventListener('change', function (event) {
            const file = event.target.files[0];
            const preview = document.getElementById('preview');
            
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    preview.src = e.target.result;
                };
                reader.readAsDataURL(file);
            }
        })
        </script>
</body>
</html>